### PR TITLE
Lazy load default value of api_client property

### LINKED ISSUE #72: Default property api_client is not evaluated using lazy
The default value for the `api` resource  is `default: lazy { ::Nexus3::Api.default(node) }`
https://github.com/criteo-cookbooks/nexus3/blob/master/resources/api.rb#L4

However, the other resources have `default: ::Nexus3::Api.default(node)`
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/repo.rb#L5
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/group.rb#L6
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/role.rb#L5
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/task.rb#L4
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/user.rb#L7

I found that in the same chef run, this caused unexpected results.

```ruby
nexus3 'nexus' do
  action :install

  notifies :create, 'nexus3_api[admin_change_password]', :immediately
  notifies :run, 'nexus3_api[admin_change_password]', :immediately
  notifies :delete, 'nexus3_api[admin_change_password]', :immediately
end

nexus3_api 'admin_change_password' do
  script_name 'admin_change_password'
  content   "security.securitySystem.changePassword('admin', args)"
  args      'some new password'
  sensitive true

  action :nothing
end

ruby_block 'update nexus api credentials' do
  block do
    # this is run at converge time so that following resources use the new password
    node.override['nexus3']['api']['password'] = 'some new password'
  end
  action :run
end

nexus3_repo "Create a repo" do
  repo_name 'new-repo'
  repo_type 'raw-hosted'
  # without this, it would fail
  api_client lazy { ::Nexus3::Api.default(node) }

  action :create
end
```

### PR DESCRIPTION
**Pull request by josh-barker**
Resolves #72

### CODE REVIEW

File: spec/unit/change_admin_password_spec.rb [hunk 1]
```diff
@@ -0,0 +1,51 @@
+require 'spec_helper'
+
+describe 'nexus3_test::change_admin_password' do
+  context 'linux' do
+    let(:chef_run) do
+      ChefSpec::SoloRunner.new(platform: 'centos', version: CENTOS_VERSION, step_into: 'nexus3',
+                               file_cache_path: CACHE).converge('nexus3_test::default', 'nexus3_test::change_admin_password')
```
Comment (Annih) [inline spec/unit/change_admin_password_spec.rb]: Please put the `.converge` call at the next line to please rubocop:
```ruby
ChefSpec::SoloRunner.new(platform: 'centos', version: CENTOS_VERSION, step_into: 'nexus3', file_cache_path: CACHE)
                    .converge('nexus3_test::default', 'nexus3_test::change_admin_password') 
```

File: spec/unit/change_admin_password_spec.rb [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+
+    it 'Update Nexus Credentials' do
+      expect(chef_run).to run_ruby_block('update nexus api credentials for future resources')
+    end
+  end
+
+  context 'windows' do
+    let(:chef_run) do
+      ChefSpec::SoloRunner.new(platform: 'windows', version: '2012R2', step_into: 'nexus3',
+                               file_cache_path: CACHE).converge('nexus3_test::default', 'nexus3_test::change_admin_password')
```
Comment (Annih) [inline spec/unit/change_admin_password_spec.rb]: Same as above:
```ruby
ChefSpec::SoloRunner.new(platform: 'windows', version: '2012R2', step_into: 'nexus3', file_cache_path: CACHE)
                    .converge('nexus3_test::default', 'nexus3_test::change_admin_password') 
```
